# Site settings
title: Paul Raj
description: 'Interested in ML and AI'
url: 'https://paulraj.github.io'
baseurl: '/'
google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'paulraj-github-io'

author:
  name: 'Paul Raj'
  email: pauldeepakrajr@gmail.com
  twitter_username: pauldeepakraj_r
  facebook_username: 
  github_username:  paulraj
  linkedin_username:  pauldeepakraj

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 1
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
